"""
Plot clear per-obstacle diagnostic figures from runtime_supervisor_log.csv.

Version 3 changes:
1) Overview figure now keeps ONLY TWO subplots:
   - Clearance
   - Speed reduction
2) Overview reduction subplot no longer shows intervention dashes.
3) Overview clearance subplot uses clearer, different colors for the
   clearance curve and the boundary/reference lines.
4) Individual obstacle figures are kept as before:
   - local path
   - clearance
   - risk
   - speed

Run:
    python plot_obstacle_diagnostics_v3.py --csv runtime_supervisor_log.csv

Optional:
    python plot_obstacle_diagnostics_v3.py --csv runtime_supervisor_log.csv --window 2.5
"""

import os
import argparse
from dataclasses import dataclass

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


@dataclass
class Obstacle:
    cx: float
    cy: float
    radius: float
    name: str


def obstacle_map():
    return [
        Obstacle(cx=-0.15, cy=0.12, radius=0.16, name="O1"),
        Obstacle(cx=0.45, cy=-0.17, radius=0.16, name="O2"),
        Obstacle(cx=1.00, cy=0.10, radius=0.16, name="O3"),
        Obstacle(cx=1.48, cy=-0.18, radius=0.16, name="O4"),
    ]


def check_required_columns(df):
    required = [
        "time_s",
        "x_m",
        "y_m",
        "current_clearance_m",
        "proximity_risk",
        "proposed_speed_mps",
        "executed_speed_mps",
        "intervention",
    ]

    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(
            "Missing required columns in CSV:\n"
            + "\n".join(missing)
            + "\n\nYour CSV should be the runtime_supervisor_log.csv generated by the supervisor code."
        )


def add_extra_diagnostics(df):
    df = df.copy()

    if "speed_reduction_mps" not in df.columns:
        df["speed_reduction_mps"] = df["proposed_speed_mps"] - df["executed_speed_mps"]

    if "speed_reduction_ratio" not in df.columns:
        df["speed_reduction_ratio"] = np.where(
            df["proposed_speed_mps"].abs() > 1e-9,
            df["speed_reduction_mps"] / df["proposed_speed_mps"],
            0.0,
        )

    return df


def get_obstacle_events(df, obstacles):
    events = []

    for obs in obstacles:
        dist_to_center = np.sqrt((df["x_m"] - obs.cx) ** 2 + (df["y_m"] - obs.cy) ** 2)
        clearance_to_this_obs = dist_to_center - obs.radius
        idx = clearance_to_this_obs.idxmin()

        events.append(
            {
                "name": obs.name,
                "idx": idx,
                "time_s": float(df.loc[idx, "time_s"]),
                "x_m": float(df.loc[idx, "x_m"]),
                "y_m": float(df.loc[idx, "y_m"]),
                "distance_to_center_m": float(dist_to_center.loc[idx]),
                "clearance_to_this_obstacle_m": float(clearance_to_this_obs.loc[idx]),
                "current_clearance_m": float(df.loc[idx, "current_clearance_m"]),
                "proximity_risk": float(df.loc[idx, "proximity_risk"]),
                "proposed_speed_mps": float(df.loc[idx, "proposed_speed_mps"]),
                "executed_speed_mps": float(df.loc[idx, "executed_speed_mps"]),
                "speed_reduction_mps": float(df.loc[idx, "speed_reduction_mps"]),
                "intervention": int(df.loc[idx, "intervention"]),
            }
        )

    return events


def add_obstacle_markers_to_axis(ax, events, y_text=0.98):
    ymin, ymax = ax.get_ylim()

    for ev in events:
        t = ev["time_s"]
        ax.axvline(t, linestyle=":", linewidth=1.1, alpha=0.75, color="tab:gray")
        ax.text(
            t,
            ymin + y_text * (ymax - ymin),
            ev["name"],
            ha="center",
            va="top",
            fontsize=8,
            fontweight="bold",
            color="black",
        )


def plot_overview(df, events, out_dir):
    """
    Global figure with 2 subplots only:
    1) Clearance with color-separated reference lines.
    2) Speed reduction only, emphasized for visibility.
    """
    fig, axes = plt.subplots(2, 1, figsize=(10, 5.8), sharex=True)

    # -----------------------------------------------------------------
    # 1) Clearance
    # -----------------------------------------------------------------
    ax = axes[0]
    ax.plot(df["time_s"], df["current_clearance_m"], linewidth=2.4, color="tab:blue", label="Clearance")
    ax.axhline(0.20, linestyle="--", linewidth=1.4, color="tab:red", label="Warning clearance")
    ax.axhline(0.05, linestyle="--", linewidth=1.4, color="tab:orange", label="Safe clearance")
    ax.axhline(0.0, linestyle="--", linewidth=1.4, color="black", label="Collision boundary")
    ax.set_ylabel("Clearance [m]")
    #ax.set_title("Full Run Diagnostic: Obstacle Passing, Clearance, and Speed Reduction")
    ax.grid(True)
    ax.legend(fontsize=8, loc="upper right")

    # -----------------------------------------------------------------
    # 2) Speed reduction only (no intervention dashes)
    # -----------------------------------------------------------------
    ax = axes[1]
    reduction = df["speed_reduction_mps"]
    ax.plot(df["time_s"], reduction, linewidth=2.5, color="tab:purple", label="Speed reduction")
    ax.fill_between(df["time_s"], 0.0, reduction, color="tab:purple", alpha=0.22)
    ax.set_ylabel("Reduction [m/s]")
    ax.set_xlabel("Time [s]")
    ax.grid(True)

    rmin = float(reduction.min())
    rmax = float(reduction.max())
    margin = max(0.004, 0.15 * (rmax - rmin + 1e-9))
    ax.set_ylim(max(0.0, rmin - margin), rmax + margin)
    ax.legend(fontsize=8, loc="upper right")

    for ax in axes:
        add_obstacle_markers_to_axis(ax, events)

    plt.tight_layout()
    fig.savefig(os.path.join(out_dir, "all_obstacles_overview.png"), dpi=300, bbox_inches="tight")
    fig.savefig(os.path.join(out_dir, "all_obstacles_overview.pdf"), bbox_inches="tight")
    plt.close(fig)


def plot_single_obstacle(df, obs, ev, out_dir, window=2.5):
    """
    Create a clear local figure for one obstacle:
    - left: local trajectory around obstacle
    - right: clearance, risk, executed/proposed speed
    """
    t0 = ev["time_s"]
    local = df[(df["time_s"] >= t0 - window) & (df["time_s"] <= t0 + window)].copy()

    if len(local) < 2:
        print(f"Warning: not enough local samples for {obs.name}")
        return

    fig = plt.figure(figsize=(10, 6.2))
    gs = fig.add_gridspec(3, 2)

    ax_path = fig.add_subplot(gs[:, 0])
    ax_clearance = fig.add_subplot(gs[0, 1])
    ax_risk = fig.add_subplot(gs[1, 1])
    ax_speed = fig.add_subplot(gs[2, 1])

    # Left: local path
    ax_path.plot(df["x_m"], df["y_m"], linewidth=1.0, alpha=0.35, label="Full trajectory")
    ax_path.plot(local["x_m"], local["y_m"], linewidth=2.5, label=f"Trajectory near {obs.name}")
    ax_path.scatter(ev["x_m"], ev["y_m"], s=45, zorder=5, label="Closest passing point")

    circle = plt.Circle((obs.cx, obs.cy), obs.radius, fill=False, linestyle="--", linewidth=2)
    ax_path.add_patch(circle)
    ax_path.scatter(obs.cx, obs.cy, marker="x", s=60)
    ax_path.text(obs.cx, obs.cy, obs.name, ha="center", va="center", fontsize=11, fontweight="bold")

    margin = 0.45
    ax_path.set_xlim(obs.cx - margin, obs.cx + margin)
    ax_path.set_ylim(obs.cy - margin, obs.cy + margin)
    ax_path.set_aspect("equal", adjustable="box")
    ax_path.set_xlabel("x position [m]")
    ax_path.set_ylabel("y position [m]")
    ax_path.set_title(f"{obs.name}: Local Path Around Obstacle")
    ax_path.grid(True)
    ax_path.legend(fontsize=8, loc="best")

    # Clearance
    ax_clearance.plot(local["time_s"], local["current_clearance_m"], linewidth=2)
    ax_clearance.axhline(0.20, linestyle="--", linewidth=1.0, label="Warning")
    ax_clearance.axhline(0.07, linestyle="--", linewidth=1.0, label="Safe")
    ax_clearance.axhline(0.0, linestyle="--", linewidth=1.0, label="Collision")
    ax_clearance.scatter(t0, ev["current_clearance_m"], s=35, zorder=5)
    ax_clearance.annotate(
        f'{ev["current_clearance_m"]:.3f} m',
        (t0, ev["current_clearance_m"]),
        textcoords="offset points",
        xytext=(7, 7),
        fontsize=8,
    )
    ax_clearance.axvline(t0, linestyle=":", linewidth=1.2)
    ax_clearance.set_ylabel("Clearance [m]")
    ax_clearance.set_title(f"{obs.name}: Clearance drops near closest passing")
    ax_clearance.grid(True)
    ax_clearance.legend(fontsize=7, loc="best")

    # Risk
    ax_risk.plot(local["time_s"], local["proximity_risk"], linewidth=2)
    ax_risk.scatter(t0, ev["proximity_risk"], s=35, zorder=5)
    ax_risk.annotate(
        f'{ev["proximity_risk"]:.2f}',
        (t0, ev["proximity_risk"]),
        textcoords="offset points",
        xytext=(7, 7),
        fontsize=8,
    )
    ax_risk.axvline(t0, linestyle=":", linewidth=1.2)
    ax_risk.set_ylabel("Risk")
    ax_risk.set_ylim(-0.05, 1.05)
    ax_risk.set_title(f"{obs.name}: Risk increases as clearance decreases")
    ax_risk.grid(True)

    # Speed
    ax_speed.plot(local["time_s"], local["proposed_speed_mps"], linestyle=":", linewidth=1.8, label="Proposed")
    ax_speed.plot(local["time_s"], local["executed_speed_mps"], linewidth=2, label="Executed")
    ax_speed.scatter(t0, ev["executed_speed_mps"], s=35, zorder=5)
    ax_speed.annotate(
        f'{ev["executed_speed_mps"]:.3f} m/s',
        (t0, ev["executed_speed_mps"]),
        textcoords="offset points",
        xytext=(7, -13),
        fontsize=8,
    )
    ax_speed.axvline(t0, linestyle=":", linewidth=1.2)
    ax_speed.set_ylabel("Speed [m/s]")
    ax_speed.set_xlabel("Time [s]")
    ax_speed.set_title(f"{obs.name}: Executed speed decreases")
    ax_speed.grid(True)
    ax_speed.legend(fontsize=8, loc="best")

    for ax in [ax_clearance, ax_risk, ax_speed]:
        ax.set_xlim(t0 - window, t0 + window)

    fig.suptitle(
        (
            f"{obs.name} diagnostic: closest time={t0:.2f}s, "
            f"clearance={ev['current_clearance_m']:.3f}m, "
            f"risk={ev['proximity_risk']:.2f}, "
            f"speed={ev['executed_speed_mps']:.3f}m/s"
        ),
        fontsize=12,
        fontweight="bold",
    )

    plt.tight_layout(rect=[0, 0, 1, 0.95])
    fig.savefig(os.path.join(out_dir, f"obstacle_{obs.name}_diagnostic.png"), dpi=300, bbox_inches="tight")
    fig.savefig(os.path.join(out_dir, f"obstacle_{obs.name}_diagnostic.pdf"), bbox_inches="tight")
    plt.close(fig)


def make_summary(events, out_dir):
    summary = pd.DataFrame(events)
    columns = [
        "name",
        "time_s",
        "x_m",
        "y_m",
        "distance_to_center_m",
        "clearance_to_this_obstacle_m",
        "current_clearance_m",
        "proximity_risk",
        "proposed_speed_mps",
        "executed_speed_mps",
        "speed_reduction_mps",
        "intervention",
    ]
    summary = summary[columns]
    summary.to_csv(os.path.join(out_dir, "obstacle_diagnostic_summary.csv"), index=False)

    print("\nObstacle diagnostic summary:")
    print(summary.to_string(index=False))
    return summary


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", default="runtime_supervisor_log.csv", help="Path to runtime_supervisor_log.csv")
    parser.add_argument("--out_dir", default="obstacle_diagnostic_figures", help="Output folder")
    parser.add_argument("--window", type=float, default=2.5, help="Seconds before/after closest obstacle passing")
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    df = pd.read_csv(args.csv)
    check_required_columns(df)
    df = add_extra_diagnostics(df)

    obstacles = obstacle_map()
    events = get_obstacle_events(df, obstacles)

    make_summary(events, args.out_dir)
    plot_overview(df, events, args.out_dir)

    for obs, ev in zip(obstacles, events):
        plot_single_obstacle(df=df, obs=obs, ev=ev, out_dir=args.out_dir, window=args.window)

    print("\nSaved diagnostic figures in:")
    print(args.out_dir)
    print("\nMain files:")
    print("  all_obstacles_overview.png / .pdf")
    for obs in obstacles:
        print(f"  obstacle_{obs.name}_diagnostic.png / .pdf")
    print("  obstacle_diagnostic_summary.csv")


if __name__ == "__main__":
    main()
